buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.palantir.gradle.jdks:gradle-jdks-settings:0.79.0'
    }
}
apply plugin: 'com.palantir.jdks.settings'
rootProject.name = 'human-readable-types-root'

include 'human-readable-types'

throw new RuntimeException('''The excavator failed to run properly:\n\n''' + file('gradle/exception').text)
